name: Tyler Hallada - Blog
description: Musings on technology, literature, and interesting topics
url: http://hallada.net/blog
assets: http://hallada.net/assets/
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
paginate: 10
paginate_path: "blog/page:num"
gems:
    - jekyll-redirect-from
    - jekyll-paginate
